{{- range .Values.templates }}
  {{- $roleName := .name }}
  {{- range .namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $roleName }}-role
  namespace: {{ . }}
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
  {{- end }}
{{- end }}