namespaces:
  - dev
  - staging
  - prod

# creates the role for the respective namespace
templates:
  - name: admin
    namespaces: 
      - dev
      - staging
      - prod

roles:
  # rolebindung to the user and the role
  admin:
    - name: namespace-admin
      namespaces:
        - dev
        - staging
        - prod
